import type { NextConfig } from "next";
import legacyBlogSlugs from "./src/data/legacyBlogSlugs.json";

// The blog is hosted on Typeflo and served under /blog (replaces Typeflo's
// Cloudflare Worker, which never ran because the domain isn't Cloudflare-proxied).
const TYPEFLO_ORIGIN = "https://science-divine.typeflo.io";
// Old WordPress posts that exist only in src/data/blogPosts.ts, not on Typeflo.
// They keep being served by src/app/blog/[slug] so their indexed URLs don't break.
const LEGACY_BLOG_SLUGS_PATTERN = (legacyBlogSlugs as string[]).join("|");

const nextConfig: NextConfig = {
  allowedDevOrigins: ["192.168.1.30"],
  typescript: {
    ignoreBuildErrors: true,
  },
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "sciencedivine.org",
      },
      {
        protocol: "https",
        hostname: "*.supabase.co",
      },
      {
        protocol: "https",
        hostname: "i.ytimg.com",
      },
    ],
  },
  // Allow requests to external media
  async headers() {
    return [
      {
        source: "/(.*)",
        headers: [
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "X-Frame-Options", value: "SAMEORIGIN" },
          { key: "X-XSS-Protection", value: "1; mode=block" },
        ],
      },
    ];
  },
  async rewrites() {
    return {
      // beforeFiles so these win over the local src/app/blog pages
      beforeFiles: [
        { source: "/blog", destination: `${TYPEFLO_ORIGIN}/blog` },
        {
          source: `/blog/:path((?!(?:${LEGACY_BLOG_SLUGS_PATTERN})$).+)`,
          destination: `${TYPEFLO_ORIGIN}/blog/:path`,
        },
        // Typeflo pages load their fonts from this relative path
        {
          source: "/_next/static/custom/fonts/:path*",
          destination: `${TYPEFLO_ORIGIN}/:path*`,
        },
      ],
    };
  },
  async redirects() {
    return [
      // ─────────────────────────────────────────────
      // PHASE 0 — Security: Hacked / spam URLs → /410
      // ─────────────────────────────────────────────
      { source: "/public/dominoqq", destination: "/410", permanent: false },
      { source: "/public/dominoqq/", destination: "/410", permanent: false },

      // ─────────────────────────────────────────────
      // PHASE 3 — Blog Posts: /{slug}/ → /blog/{slug}/
      // All 91 WordPress blog posts were at root level.
      // ─────────────────────────────────────────────
      { source: "/7-chakras-of-body", destination: "/blog/7-chakras-of-body", permanent: true },
      { source: "/7-chakras-of-body/", destination: "/blog/7-chakras-of-body", permanent: true },
      { source: "/ajna-chakra", destination: "/blog/ajna-chakra", permanent: true },
      { source: "/ajna-chakra/", destination: "/blog/ajna-chakra", permanent: true },
      { source: "/anahata-chakra", destination: "/blog/anahata-chakra", permanent: true },
      { source: "/anahata-chakra/", destination: "/blog/anahata-chakra", permanent: true },
      { source: "/asana-for-high-blood-pressure", destination: "/blog/asana-for-high-blood-pressure", permanent: true },
      { source: "/asana-for-high-blood-pressure/", destination: "/blog/asana-for-high-blood-pressure", permanent: true },
      { source: "/basics-of-meditation", destination: "/blog/basics-of-meditation", permanent: true },
      { source: "/basics-of-meditation/", destination: "/blog/basics-of-meditation", permanent: true },
      { source: "/benefits-of-meditation", destination: "/blog/benefits-of-meditation", permanent: true },
      { source: "/benefits-of-meditation/", destination: "/blog/benefits-of-meditation", permanent: true },
      { source: "/build-mental-power", destination: "/blog/build-mental-power", permanent: true },
      { source: "/build-mental-power/", destination: "/blog/build-mental-power", permanent: true },
      { source: "/chakras-in-human-body", destination: "/blog/chakras-in-human-body", permanent: true },
      { source: "/chakras-in-human-body/", destination: "/blog/chakras-in-human-body", permanent: true },
      { source: "/change-your-destiny", destination: "/blog/change-your-destiny", permanent: true },
      { source: "/change-your-destiny/", destination: "/blog/change-your-destiny", permanent: true },
      { source: "/coming-soon-course", destination: "/courses", permanent: true },
      { source: "/coming-soon-course/", destination: "/courses", permanent: true },
      { source: "/connect-with-the-divine-power", destination: "/blog/connect-with-the-divine-power", permanent: true },
      { source: "/connect-with-the-divine-power/", destination: "/blog/connect-with-the-divine-power", permanent: true },
      { source: "/conscious-mind-and-subconscious-mind", destination: "/blog/conscious-mind-and-subconscious-mind", permanent: true },
      { source: "/conscious-mind-and-subconscious-mind/", destination: "/blog/conscious-mind-and-subconscious-mind", permanent: true },
      { source: "/conscious", destination: "/blog/conscious", permanent: true },
      { source: "/conscious/", destination: "/blog/conscious", permanent: true },
      { source: "/declutter-your-mind-and-cleanse-your-soul", destination: "/blog/declutter-your-mind-and-cleanse-your-soul", permanent: true },
      { source: "/declutter-your-mind-and-cleanse-your-soul/", destination: "/blog/declutter-your-mind-and-cleanse-your-soul", permanent: true },
      { source: "/deep-breathing-for-better-brain", destination: "/blog/deep-breathing-for-better-brain", permanent: true },
      { source: "/deep-breathing-for-better-brain/", destination: "/blog/deep-breathing-for-better-brain", permanent: true },
      { source: "/deep-connection-between-meditation-and-the-soul", destination: "/blog/deep-connection-between-meditation-and-the-soul", permanent: true },
      { source: "/deep-connection-between-meditation-and-the-soul/", destination: "/blog/deep-connection-between-meditation-and-the-soul", permanent: true },
      { source: "/deepening-connection-in-marriage", destination: "/blog/deepening-connection-in-marriage", permanent: true },
      { source: "/deepening-connection-in-marriage/", destination: "/blog/deepening-connection-in-marriage", permanent: true },
      { source: "/embark-on-your-meditation-journey", destination: "/blog/embark-on-your-meditation-journey", permanent: true },
      { source: "/embark-on-your-meditation-journey/", destination: "/blog/embark-on-your-meditation-journey", permanent: true },
      { source: "/feminine-energy", destination: "/blog/feminine-energy", permanent: true },
      { source: "/feminine-energy/", destination: "/blog/feminine-energy", permanent: true },
      { source: "/five-effective-yoga-poses", destination: "/blog/five-effective-yoga-poses", permanent: true },
      { source: "/five-effective-yoga-poses/", destination: "/blog/five-effective-yoga-poses", permanent: true },
      { source: "/gateway-to-nirvana", destination: "/blog/gateway-to-nirvana", permanent: true },
      { source: "/gateway-to-nirvana/", destination: "/blog/gateway-to-nirvana", permanent: true },
      { source: "/gomti-chakra", destination: "/blog/gomti-chakra", permanent: true },
      { source: "/gomti-chakra/", destination: "/blog/gomti-chakra", permanent: true },
      { source: "/habits-that-can-change-your-life", destination: "/blog/habits-that-can-change-your-life", permanent: true },
      { source: "/habits-that-can-change-your-life/", destination: "/blog/habits-that-can-change-your-life", permanent: true },
      { source: "/harmonizing-mind-and-body", destination: "/blog/harmonizing-mind-and-body", permanent: true },
      { source: "/harmonizing-mind-and-body/", destination: "/blog/harmonizing-mind-and-body", permanent: true },
      { source: "/healing-after-failed-love", destination: "/blog/healing-after-failed-love", permanent: true },
      { source: "/healing-after-failed-love/", destination: "/blog/healing-after-failed-love", permanent: true },
      { source: "/hello-world", destination: "/blog", permanent: true },
      { source: "/hello-world/", destination: "/blog", permanent: true },
      { source: "/how-energy-flow-shapes-your-physical", destination: "/blog/how-energy-flow-shapes-your-physical", permanent: true },
      { source: "/how-energy-flow-shapes-your-physical/", destination: "/blog/how-energy-flow-shapes-your-physical", permanent: true },
      { source: "/how-to-make-life-a-game", destination: "/blog/how-to-make-life-a-game", permanent: true },
      { source: "/how-to-make-life-a-game/", destination: "/blog/how-to-make-life-a-game", permanent: true },
      { source: "/impact-of-spirituality-on-academic-pursuits", destination: "/blog/impact-of-spirituality-on-academic-pursuits", permanent: true },
      { source: "/impact-of-spirituality-on-academic-pursuits/", destination: "/blog/impact-of-spirituality-on-academic-pursuits", permanent: true },
      { source: "/manipura-chakra", destination: "/blog/manipura-chakra", permanent: true },
      { source: "/manipura-chakra/", destination: "/blog/manipura-chakra", permanent: true },
      { source: "/master-art-of-deep-relaxation", destination: "/blog/master-art-of-deep-relaxation", permanent: true },
      { source: "/master-art-of-deep-relaxation/", destination: "/blog/master-art-of-deep-relaxation", permanent: true },
      { source: "/master-your-own-fate", destination: "/blog/master-your-own-fate", permanent: true },
      { source: "/master-your-own-fate/", destination: "/blog/master-your-own-fate", permanent: true },
      { source: "/mastering-calm", destination: "/blog/mastering-calm", permanent: true },
      { source: "/mastering-calm/", destination: "/blog/mastering-calm", permanent: true },
      { source: "/mastering-life-s-challenges", destination: "/blog/mastering-life-s-challenges", permanent: true },
      { source: "/mastering-life-s-challenges/", destination: "/blog/mastering-life-s-challenges", permanent: true },
      { source: "/meditation-and-mental-health", destination: "/blog/meditation-and-mental-health", permanent: true },
      { source: "/meditation-and-mental-health/", destination: "/blog/meditation-and-mental-health", permanent: true },
      { source: "/meditation-at-home", destination: "/blog/meditation-at-home", permanent: true },
      { source: "/meditation-at-home/", destination: "/blog/meditation-at-home", permanent: true },
      { source: "/meditation-for-kids", destination: "/blog/meditation-for-kids", permanent: true },
      { source: "/meditation-for-kids/", destination: "/blog/meditation-for-kids", permanent: true },
      { source: "/meditation-for-seniors", destination: "/blog/meditation-for-seniors", permanent: true },
      { source: "/meditation-for-seniors/", destination: "/blog/meditation-for-seniors", permanent: true },
      { source: "/meditation-into-your-daily-routine", destination: "/blog/meditation-into-your-daily-routine", permanent: true },
      { source: "/meditation-into-your-daily-routine/", destination: "/blog/meditation-into-your-daily-routine", permanent: true },
      { source: "/muladhara-chakra", destination: "/blog/muladhara-chakra", permanent: true },
      { source: "/muladhara-chakra/", destination: "/blog/muladhara-chakra", permanent: true },
      { source: "/negative-loop-of-mind", destination: "/blog/negative-loop-of-mind", permanent: true },
      { source: "/negative-loop-of-mind/", destination: "/blog/negative-loop-of-mind", permanent: true },
      { source: "/negativity-within-family", destination: "/blog/negativity-within-family", permanent: true },
      { source: "/negativity-within-family/", destination: "/blog/negativity-within-family", permanent: true },
      { source: "/optimistic-mind", destination: "/blog/optimistic-mind", permanent: true },
      { source: "/optimistic-mind/", destination: "/blog/optimistic-mind", permanent: true },
      { source: "/power-of-law-of-attraction", destination: "/blog/power-of-law-of-attraction", permanent: true },
      { source: "/power-of-law-of-attraction/", destination: "/blog/power-of-law-of-attraction", permanent: true },
      // Fix WP typo: "manifestaion" → "manifestation"
      { source: "/power-of-manifestaion", destination: "/blog/power-of-manifestation-for-your-dream-life", permanent: true },
      { source: "/power-of-manifestaion/", destination: "/blog/power-of-manifestation-for-your-dream-life", permanent: true },
      { source: "/power-of-manifestation-for-your-dream-life", destination: "/blog/power-of-manifestation-for-your-dream-life", permanent: true },
      { source: "/power-of-manifestation-for-your-dream-life/", destination: "/blog/power-of-manifestation-for-your-dream-life", permanent: true },
      { source: "/power-of-spirituality-in-self-discovery", destination: "/blog/power-of-spirituality-in-self-discovery", permanent: true },
      { source: "/power-of-spirituality-in-self-discovery/", destination: "/blog/power-of-spirituality-in-self-discovery", permanent: true },
      { source: "/prana-energy-or-soul-energy", destination: "/blog/prana-energy-or-soul-energy", permanent: true },
      { source: "/prana-energy-or-soul-energy/", destination: "/blog/prana-energy-or-soul-energy", permanent: true },
      { source: "/pranayama-for-high-blood-pressure", destination: "/blog/pranayama-for-high-blood-pressure", permanent: true },
      { source: "/pranayama-for-high-blood-pressure/", destination: "/blog/pranayama-for-high-blood-pressure", permanent: true },
      { source: "/sahasrara-chakra", destination: "/blog/sahasrara-chakra", permanent: true },
      { source: "/sahasrara-chakra/", destination: "/blog/sahasrara-chakra", permanent: true },
      { source: "/seven-chakras", destination: "/blog/seven-chakras", permanent: true },
      { source: "/seven-chakras/", destination: "/blog/seven-chakras", permanent: true },
      // Deduplicate: silence-isnt-empty-its-full-2 → canonical version
      { source: "/silence-isnt-empty-its-full-2", destination: "/blog/silence-isnt-empty-its-full", permanent: true },
      { source: "/silence-isnt-empty-its-full-2/", destination: "/blog/silence-isnt-empty-its-full", permanent: true },
      { source: "/silence-isnt-empty-its-full", destination: "/blog/silence-isnt-empty-its-full", permanent: true },
      { source: "/silence-isnt-empty-its-full/", destination: "/blog/silence-isnt-empty-its-full", permanent: true },
      { source: "/silent-retreats-unveiled", destination: "/blog/silent-retreats-unveiled", permanent: true },
      { source: "/silent-retreats-unveiled/", destination: "/blog/silent-retreats-unveiled", permanent: true },
      { source: "/spiritual-practises-to-tackle-loneliness", destination: "/blog/spiritual-practises-to-tackle-loneliness", permanent: true },
      { source: "/spiritual-practises-to-tackle-loneliness/", destination: "/blog/spiritual-practises-to-tackle-loneliness", permanent: true },
      { source: "/spirituality-and-materialism", destination: "/blog/spirituality-and-materialism", permanent: true },
      { source: "/spirituality-and-materialism/", destination: "/blog/spirituality-and-materialism", permanent: true },
      { source: "/spiritualitys-role-in-healing-childhood-trauma", destination: "/blog/spiritualitys-role-in-healing-childhood-trauma", permanent: true },
      { source: "/spiritualitys-role-in-healing-childhood-trauma/", destination: "/blog/spiritualitys-role-in-healing-childhood-trauma", permanent: true },
      { source: "/stop-negative-thinking", destination: "/blog/stop-negative-thinking", permanent: true },
      { source: "/stop-negative-thinking/", destination: "/blog/stop-negative-thinking", permanent: true },
      { source: "/stress-reduction", destination: "/blog/stress-reduction", permanent: true },
      { source: "/stress-reduction/", destination: "/blog/stress-reduction", permanent: true },
      { source: "/svadhisthana-chakra", destination: "/blog/svadhisthana-chakra", permanent: true },
      { source: "/svadhisthana-chakra/", destination: "/blog/svadhisthana-chakra", permanent: true },
      { source: "/the-art-of-observation", destination: "/blog/the-art-of-observation", permanent: true },
      { source: "/the-art-of-observation/", destination: "/blog/the-art-of-observation", permanent: true },
      { source: "/the-science-of-breathing", destination: "/blog/the-science-of-breathing", permanent: true },
      { source: "/the-science-of-breathing/", destination: "/blog/the-science-of-breathing", permanent: true },
      { source: "/unlock-a-productive-day", destination: "/blog/unlock-a-productive-day", permanent: true },
      { source: "/unlock-a-productive-day/", destination: "/blog/unlock-a-productive-day", permanent: true },
      { source: "/unlock-restful-nights", destination: "/blog/unlock-restful-nights", permanent: true },
      { source: "/unlock-restful-nights/", destination: "/blog/unlock-restful-nights", permanent: true },
      { source: "/unlock-the-power-of-guided-meditation", destination: "/blog/unlock-the-power-of-guided-meditation", permanent: true },
      { source: "/unlock-the-power-of-guided-meditation/", destination: "/blog/unlock-the-power-of-guided-meditation", permanent: true },
      { source: "/unlock-the-power-of-your-mind", destination: "/blog/unlock-the-power-of-your-mind", permanent: true },
      { source: "/unlock-the-power-of-your-mind/", destination: "/blog/unlock-the-power-of-your-mind", permanent: true },
      { source: "/unlock-your-inner-harmony", destination: "/blog/unlock-your-inner-harmony", permanent: true },
      { source: "/unlock-your-inner-harmony/", destination: "/blog/unlock-your-inner-harmony", permanent: true },
      { source: "/unlocking-creative-genius", destination: "/blog/unlocking-creative-genius", permanent: true },
      { source: "/unlocking-creative-genius/", destination: "/blog/unlocking-creative-genius", permanent: true },
      { source: "/unlocking-harmony", destination: "/blog/unlocking-harmony", permanent: true },
      { source: "/unlocking-harmony/", destination: "/blog/unlocking-harmony", permanent: true },
      { source: "/unlocking-wellness", destination: "/blog/unlocking-wellness", permanent: true },
      { source: "/unlocking-wellness/", destination: "/blog/unlocking-wellness", permanent: true },
      { source: "/unravelling-the-power-of-meditation", destination: "/blog/unravelling-the-power-of-meditation", permanent: true },
      { source: "/unravelling-the-power-of-meditation/", destination: "/blog/unravelling-the-power-of-meditation", permanent: true },
      { source: "/unveiling-the-harmony", destination: "/blog/unveiling-the-harmony", permanent: true },
      { source: "/unveiling-the-harmony/", destination: "/blog/unveiling-the-harmony", permanent: true },
      { source: "/vishuddha-chakra", destination: "/blog/vishuddha-chakra", permanent: true },
      { source: "/vishuddha-chakra/", destination: "/blog/vishuddha-chakra", permanent: true },
      { source: "/what-is-brahma-muhurta", destination: "/blog/what-is-brahma-muhurta", permanent: true },
      { source: "/what-is-brahma-muhurta/", destination: "/blog/what-is-brahma-muhurta", permanent: true },
      { source: "/what-is-conscious-mind", destination: "/blog/what-is-conscious-mind", permanent: true },
      { source: "/what-is-conscious-mind/", destination: "/blog/what-is-conscious-mind", permanent: true },
      { source: "/what-is-consciousness", destination: "/blog/what-is-consciousness", permanent: true },
      { source: "/what-is-consciousness/", destination: "/blog/what-is-consciousness", permanent: true },
      { source: "/what-is-manifestation", destination: "/blog/what-is-manifestation", permanent: true },
      { source: "/what-is-manifestation/", destination: "/blog/what-is-manifestation", permanent: true },
      { source: "/what-is-mental-health", destination: "/blog/what-is-mental-health", permanent: true },
      { source: "/what-is-mental-health/", destination: "/blog/what-is-mental-health", permanent: true },
      { source: "/what-is-peace-of-mind", destination: "/blog/what-is-peace-of-mind", permanent: true },
      { source: "/what-is-peace-of-mind/", destination: "/blog/what-is-peace-of-mind", permanent: true },
      { source: "/what-is-positive-thinking", destination: "/blog/what-is-positive-thinking", permanent: true },
      { source: "/what-is-positive-thinking/", destination: "/blog/what-is-positive-thinking", permanent: true },
      { source: "/what-is-spiritual-healing", destination: "/blog/what-is-spiritual-healing", permanent: true },
      { source: "/what-is-spiritual-healing/", destination: "/blog/what-is-spiritual-healing", permanent: true },
      { source: "/what-is-spiritual", destination: "/blog/what-is-spiritual", permanent: true },
      { source: "/what-is-spiritual/", destination: "/blog/what-is-spiritual", permanent: true },
      { source: "/what-is-spirituality", destination: "/blog/what-is-spirituality", permanent: true },
      { source: "/what-is-spirituality/", destination: "/blog/what-is-spirituality", permanent: true },
      { source: "/why-no-one-understands-you", destination: "/blog/why-no-one-understands-you", permanent: true },
      { source: "/why-no-one-understands-you/", destination: "/blog/why-no-one-understands-you", permanent: true },
      { source: "/yoga-for-back-pain-relief", destination: "/blog/yoga-for-back-pain-relief", permanent: true },
      { source: "/yoga-for-back-pain-relief/", destination: "/blog/yoga-for-back-pain-relief", permanent: true },
      { source: "/yoga-for-flexibility", destination: "/blog/yoga-for-flexibility", permanent: true },
      { source: "/yoga-for-flexibility/", destination: "/blog/yoga-for-flexibility", permanent: true },
      { source: "/yoga-for-high-bp", destination: "/blog/yoga-for-high-bp", permanent: true },
      { source: "/yoga-for-high-bp/", destination: "/blog/yoga-for-high-bp", permanent: true },
      { source: "/yoga-for-hypertension", destination: "/blog/yoga-for-hypertension", permanent: true },
      { source: "/yoga-for-hypertension/", destination: "/blog/yoga-for-hypertension", permanent: true },
      { source: "/yoga-for-peace-of-mind", destination: "/blog/yoga-for-peace-of-mind", permanent: true },
      { source: "/yoga-for-peace-of-mind/", destination: "/blog/yoga-for-peace-of-mind", permanent: true },
      { source: "/yoga-for-weight-loss", destination: "/blog/yoga-for-weight-loss", permanent: true },
      { source: "/yoga-for-weight-loss/", destination: "/blog/yoga-for-weight-loss", permanent: true },
      { source: "/yoga-nidra", destination: "/blog/yoga-nidra", permanent: true },
      { source: "/yoga-nidra/", destination: "/blog/yoga-nidra", permanent: true },

      // ─────────────────────────────────────────────
      // PHASE 3 — Page Renames / Path Mismatches
      // ─────────────────────────────────────────────
      { source: "/about-science-divine-movement", destination: "/about-movement", permanent: true },
      { source: "/about-science-divine-movement/", destination: "/about-movement", permanent: true },
      { source: "/cancellation-and-refund-policy", destination: "/cancellation-policy", permanent: true },
      { source: "/cancellation-and-refund-policy/", destination: "/cancellation-policy", permanent: true },
      { source: "/terms-and-conditions", destination: "/terms-conditions", permanent: true },
      { source: "/terms-and-conditions/", destination: "/terms-conditions", permanent: true },
      { source: "/event-new", destination: "/events", permanent: true },
      { source: "/event-new/", destination: "/events", permanent: true },
      { source: "/session", destination: "/personal-session", permanent: true },
      { source: "/session/", destination: "/personal-session", permanent: true },
      { source: "/relationship", destination: "/relationships", permanent: true },
      { source: "/relationship/", destination: "/relationships", permanent: true },
      { source: "/new-har-ghar-shiksha", destination: "/har-ghar-shiksha", permanent: true },
      { source: "/new-har-ghar-shiksha/", destination: "/har-ghar-shiksha", permanent: true },

      // ─────────────────────────────────────────────
      // PHASE 3 — Duplicate / Alias Consolidation
      // ─────────────────────────────────────────────
      { source: "/design-your-destiny-2", destination: "/design-your-destiny", permanent: true },
      { source: "/design-your-destiny-2/", destination: "/design-your-destiny", permanent: true },
      { source: "/designyourdestiny", destination: "/design-your-destiny", permanent: true },
      { source: "/designyourdestiny/", destination: "/design-your-destiny", permanent: true },
      { source: "/design-your-destiny-event-landing-page", destination: "/design-your-destiny", permanent: true },
      { source: "/design-your-destiny-event-landing-page/", destination: "/design-your-destiny", permanent: true },
      { source: "/sanjeevni-kriya-2", destination: "/sanjeevni-kriya", permanent: true },
      { source: "/sanjeevni-kriya-2/", destination: "/sanjeevni-kriya", permanent: true },
      { source: "/sanjeevni-kriya-old", destination: "/sanjeevni-kriya", permanent: true },
      { source: "/sanjeevni-kriya-old/", destination: "/sanjeevni-kriya", permanent: true },
      { source: "/sanjeevi-kriya-landing-page", destination: "/sanjeevni-kriya", permanent: true },
      { source: "/sanjeevi-kriya-landing-page/", destination: "/sanjeevni-kriya", permanent: true },
      { source: "/science-of-joyful-living-march", destination: "/science-of-joyful-living", permanent: true },
      { source: "/science-of-joyful-living-march/", destination: "/science-of-joyful-living", permanent: true },
      { source: "/the-science-of-joyful-living", destination: "/science-of-joyful-living", permanent: true },
      { source: "/the-science-of-joyful-living/", destination: "/science-of-joyful-living", permanent: true },
      { source: "/the-science-of-joyful-living-landing-page", destination: "/science-of-joyful-living", permanent: true },
      { source: "/the-science-of-joyful-living-landing-page/", destination: "/science-of-joyful-living", permanent: true },
      { source: "/mind-power-meditation-2", destination: "/mind-power-meditation", permanent: true },
      { source: "/mind-power-meditation-2/", destination: "/mind-power-meditation", permanent: true },
      { source: "/mind-power-meditation-landing-page", destination: "/mind-power-meditation", permanent: true },
      { source: "/mind-power-meditation-landing-page/", destination: "/mind-power-meditation", permanent: true },
      // shiksha-sewa → har-ghar-shiksha (merged initiative)
      { source: "/shiksha-sewa", destination: "/har-ghar-shiksha", permanent: true },
      { source: "/shiksha-sewa/", destination: "/har-ghar-shiksha", permanent: true },

      // ─────────────────────────────────────────────
      // PHASE 3 — Obsolete / WooCommerce-only pages
      // ─────────────────────────────────────────────
      { source: "/sample-page", destination: "/410", permanent: false },
      { source: "/sample-page/", destination: "/410", permanent: false },
      { source: "/new-sample-page", destination: "/410", permanent: false },
      { source: "/new-sample-page/", destination: "/410", permanent: false },
      { source: "/sample-design", destination: "/410", permanent: false },
      { source: "/sample-design/", destination: "/410", permanent: false },
      { source: "/elementor-28339", destination: "/410", permanent: false },
      { source: "/elementor-28339/", destination: "/410", permanent: false },
      { source: "/testing-form-page", destination: "/410", permanent: false },
      { source: "/testing-form-page/", destination: "/410", permanent: false },
      { source: "/thankyou-page", destination: "/thank-you", permanent: true },
      { source: "/thankyou-page/", destination: "/thank-you", permanent: true },
      { source: "/sitemap.html", destination: "/sitemap.xml", permanent: true },
      { source: "/checkout", destination: "/courses", permanent: true },
      { source: "/checkout/", destination: "/courses", permanent: true },
      { source: "/donor-dashboard", destination: "/my-account", permanent: true },
      { source: "/donor-dashboard/", destination: "/my-account", permanent: true },
      { source: "/home-copy", destination: "/", permanent: true },
      { source: "/home-copy/", destination: "/", permanent: true },
      { source: "/landing-page-copy-2", destination: "/", permanent: true },
      { source: "/landing-page-copy-2/", destination: "/", permanent: true },
      { source: "/video", destination: "/", permanent: true },
      { source: "/video/", destination: "/", permanent: true },
      { source: "/volunteer-information", destination: "/har-ghar-shiksha-volunteers", permanent: true },
      { source: "/volunteer-information/", destination: "/har-ghar-shiksha-volunteers", permanent: true },
      { source: "/us-personal-session", destination: "/personal-session", permanent: true },
      { source: "/us-personal-session/", destination: "/personal-session", permanent: true },
      { source: "/join-sunday-event", destination: "/events", permanent: true },
      { source: "/join-sunday-event/", destination: "/events", permanent: true },

      // ─────────────────────────────────────────────
      // PRESERVED — Existing blog slug renames
      // ─────────────────────────────────────────────
      { source: "/blog/how-to-reduce-stress-7-powerful-lessons-from-lord-ganesha", destination: "/blog/how-to-reduce-stress-lord-ganesha-lessons", permanent: true },
      { source: "/blog/how-to-stop-overthinking-7-bhagavad-gita-lessons-for-a-calm-mind", destination: "/blog/how-to-stop-overthinking-bhagavad-gita", permanent: true },
      { source: "/blog/vishwakarma-puja-mantra-powerful-chants", destination: "/blog/vishwakarma-puja-mantra", permanent: true },
      { source: "/blog/hartalika-teej-vrat-katha-and-puja-vidhi", destination: "/blog/hartalika-teej-story-parvati-tapasya-shiva", permanent: true },
      { source: "/blog/durva-grass-offering-to-lord-ganesha-spiritual-meaning", destination: "/blog/why-durva-is-offered-to-ganesha", permanent: true },
      { source: "/blog/why-modak-is-lord-ganeshas-favorite-sweet", destination: "/blog/why-modak-is-ganeshas-favourite-sweet", permanent: true },
      { source: "/blog/14-knots-anant-sutra-significance-on-anant-chaturdashi", destination: "/blog/why-14-knots-tied-anant-sutra-anant-chaturdashi", permanent: true },
      { source: "/blog/can-women-perform-shraddha-in-pitru-paksha", destination: "/blog/can-women-perform-shraddha-pitru-paksha", permanent: true },
      { source: "/blog/108-sacred-names-of-lord-ganesha-and-their-meanings", destination: "/blog/108-names-of-lord-ganesha-with-meaning", permanent: true },
      { source: "/blog/parsva-ekadashi-vrat-katha-and-spiritual-benefits", destination: "/blog/parsva-ekadashi-2026-vrat-katha-puja-vidhi", permanent: true },
      { source: "/blog/radha-krishna-eternal-love-story-and-spiritual-secrets", destination: "/blog/radha-krishna-love-story-spiritual-meaning-eternal-love", permanent: true },
      { source: "/blog/pitru-paksha-spiritual-significance-and-gratitude", destination: "/blog/pitru-paksha-2026-meaning-significance-science-of-gratitude", permanent: true },
    ];
  },
};

export default nextConfig;
