/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutMovementRouteImport } from './routes/about-movement'
import { Route as AboutSakshiShreeRouteImport } from './routes/about-sakshi-shree'
import { Route as AboutScienceDivineMovementRouteImport } from './routes/about-science-divine-movement'
import { Route as AddictionsRouteImport } from './routes/addictions'
import { Route as AnnapurnaSewaRouteImport } from './routes/annapurna-sewa'
import { Route as AnxietyRouteImport } from './routes/anxiety'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BirthdayEventRouteImport } from './routes/birthday-event'
import { Route as BookSessionRouteImport } from './routes/book-session'
import { Route as CancellationAndRefundPolicyRouteImport } from './routes/cancellation-and-refund-policy'
import { Route as CancellationPolicyRouteImport } from './routes/cancellation-policy'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as DepressionRouteImport } from './routes/depression'
import { Route as DesignYourDestinyRouteImport } from './routes/design-your-destiny'
import { Route as DesignYourDestiny2RouteImport } from './routes/design-your-destiny-2'
import { Route as DesignyourdestinyRouteImport } from './routes/designyourdestiny'
import { Route as DhyanSewaRouteImport } from './routes/dhyan-sewa'
import { Route as EducationSewaRouteImport } from './routes/education-sewa'
import { Route as EventNewRouteImport } from './routes/event-new'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EventsGalleryRouteImport } from './routes/events-gallery'
import { Route as FindingPurposeRouteImport } from './routes/finding-purpose'
import { Route as GetSolutionsForRouteImport } from './routes/get-solutions-for'
import { Route as GetStartedWithRouteImport } from './routes/get-started-with'
import { Route as GratitudeRouteImport } from './routes/gratitude'
import { Route as HarGharShikshaRouteImport } from './routes/har-ghar-shiksha'
import { Route as HarGharShikshaVolunteersRouteImport } from './routes/har-ghar-shiksha-volunteers'
import { Route as InitiativesRouteImport } from './routes/initiatives'
import { Route as LatestTestimonialsVideosRouteImport } from './routes/latest-testimonials-videos'
import { Route as ManifestationRouteImport } from './routes/manifestation'
import { Route as MeditationRouteImport } from './routes/meditation'
import { Route as MindPowerMeditationRouteImport } from './routes/mind-power-meditation'
import { Route as MindfulnessRouteImport } from './routes/mindfulness'
import { Route as MyAccountRouteImport } from './routes/my-account'
import { Route as NirmanSewaRouteImport } from './routes/nirman-sewa'
import { Route as OverthinkingRouteImport } from './routes/overthinking'
import { Route as ParentingRouteImport } from './routes/parenting'
import { Route as PersonalSessionRouteImport } from './routes/personal-session'
import { Route as PositiveThinkingRouteImport } from './routes/positive-thinking'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RelationshipRouteImport } from './routes/relationship'
import { Route as SanjeevniKriyaRouteImport } from './routes/sanjeevni-kriya'
import { Route as SanjeevniKriya2RouteImport } from './routes/sanjeevni-kriya-2'
import { Route as ScienceOfJoyfulLivingRouteImport } from './routes/science-of-joyful-living'
import { Route as ScienceOfJoyfulLivingMarchRouteImport } from './routes/science-of-joyful-living-march'
import { Route as ShikshaSewaRouteImport } from './routes/shiksha-sewa'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SleepingDisorderRouteImport } from './routes/sleeping-disorder'
import { Route as StressRouteImport } from './routes/stress'
import { Route as SundayEvent1FebruaryRouteImport } from './routes/sunday-event-1-february'
import { Route as SundayEvent1MarchRouteImport } from './routes/sunday-event-1-march'
import { Route as SundayEvent3MayRouteImport } from './routes/sunday-event-3-may'
import { Route as SundayEvent4JanuaryRouteImport } from './routes/sunday-event-4-january'
import { Route as SundayEvent5AprilRouteImport } from './routes/sunday-event-5-april'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as TermsConditionsRouteImport } from './routes/terms-conditions'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as UsPersonalSessionRouteImport } from './routes/us-personal-session'
import { Route as WellnessRouteImport } from './routes/wellness'
import { Route as YogaRouteImport } from './routes/yoga'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMovementRoute = AboutMovementRouteImport.update({
  id: '/about-movement',
  path: '/about-movement',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutSakshiShreeRoute = AboutSakshiShreeRouteImport.update({
  id: '/about-sakshi-shree',
  path: '/about-sakshi-shree',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutScienceDivineMovementRoute =
  AboutScienceDivineMovementRouteImport.update({
    id: '/about-science-divine-movement',
    path: '/about-science-divine-movement',
    getParentRoute: () => rootRouteImport,
  } as any)
const AddictionsRoute = AddictionsRouteImport.update({
  id: '/addictions',
  path: '/addictions',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnapurnaSewaRoute = AnnapurnaSewaRouteImport.update({
  id: '/annapurna-sewa',
  path: '/annapurna-sewa',
  getParentRoute: () => rootRouteImport,
} as any)
const AnxietyRoute = AnxietyRouteImport.update({
  id: '/anxiety',
  path: '/anxiety',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BirthdayEventRoute = BirthdayEventRouteImport.update({
  id: '/birthday-event',
  path: '/birthday-event',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSessionRoute = BookSessionRouteImport.update({
  id: '/book-session',
  path: '/book-session',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationAndRefundPolicyRoute =
  CancellationAndRefundPolicyRouteImport.update({
    id: '/cancellation-and-refund-policy',
    path: '/cancellation-and-refund-policy',
    getParentRoute: () => rootRouteImport,
  } as any)
const CancellationPolicyRoute = CancellationPolicyRouteImport.update({
  id: '/cancellation-policy',
  path: '/cancellation-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const DepressionRoute = DepressionRouteImport.update({
  id: '/depression',
  path: '/depression',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignYourDestinyRoute = DesignYourDestinyRouteImport.update({
  id: '/design-your-destiny',
  path: '/design-your-destiny',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignYourDestiny2Route = DesignYourDestiny2RouteImport.update({
  id: '/design-your-destiny-2',
  path: '/design-your-destiny-2',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignyourdestinyRoute = DesignyourdestinyRouteImport.update({
  id: '/designyourdestiny',
  path: '/designyourdestiny',
  getParentRoute: () => rootRouteImport,
} as any)
const DhyanSewaRoute = DhyanSewaRouteImport.update({
  id: '/dhyan-sewa',
  path: '/dhyan-sewa',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationSewaRoute = EducationSewaRouteImport.update({
  id: '/education-sewa',
  path: '/education-sewa',
  getParentRoute: () => rootRouteImport,
} as any)
const EventNewRoute = EventNewRouteImport.update({
  id: '/event-new',
  path: '/event-new',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsGalleryRoute = EventsGalleryRouteImport.update({
  id: '/events-gallery',
  path: '/events-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingPurposeRoute = FindingPurposeRouteImport.update({
  id: '/finding-purpose',
  path: '/finding-purpose',
  getParentRoute: () => rootRouteImport,
} as any)
const GetSolutionsForRoute = GetSolutionsForRouteImport.update({
  id: '/get-solutions-for',
  path: '/get-solutions-for',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedWithRoute = GetStartedWithRouteImport.update({
  id: '/get-started-with',
  path: '/get-started-with',
  getParentRoute: () => rootRouteImport,
} as any)
const GratitudeRoute = GratitudeRouteImport.update({
  id: '/gratitude',
  path: '/gratitude',
  getParentRoute: () => rootRouteImport,
} as any)
const HarGharShikshaRoute = HarGharShikshaRouteImport.update({
  id: '/har-ghar-shiksha',
  path: '/har-ghar-shiksha',
  getParentRoute: () => rootRouteImport,
} as any)
const HarGharShikshaVolunteersRoute =
  HarGharShikshaVolunteersRouteImport.update({
    id: '/har-ghar-shiksha-volunteers',
    path: '/har-ghar-shiksha-volunteers',
    getParentRoute: () => rootRouteImport,
  } as any)
const InitiativesRoute = InitiativesRouteImport.update({
  id: '/initiatives',
  path: '/initiatives',
  getParentRoute: () => rootRouteImport,
} as any)
const LatestTestimonialsVideosRoute =
  LatestTestimonialsVideosRouteImport.update({
    id: '/latest-testimonials-videos',
    path: '/latest-testimonials-videos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ManifestationRoute = ManifestationRouteImport.update({
  id: '/manifestation',
  path: '/manifestation',
  getParentRoute: () => rootRouteImport,
} as any)
const MeditationRoute = MeditationRouteImport.update({
  id: '/meditation',
  path: '/meditation',
  getParentRoute: () => rootRouteImport,
} as any)
const MindPowerMeditationRoute = MindPowerMeditationRouteImport.update({
  id: '/mind-power-meditation',
  path: '/mind-power-meditation',
  getParentRoute: () => rootRouteImport,
} as any)
const MindfulnessRoute = MindfulnessRouteImport.update({
  id: '/mindfulness',
  path: '/mindfulness',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAccountRoute = MyAccountRouteImport.update({
  id: '/my-account',
  path: '/my-account',
  getParentRoute: () => rootRouteImport,
} as any)
const NirmanSewaRoute = NirmanSewaRouteImport.update({
  id: '/nirman-sewa',
  path: '/nirman-sewa',
  getParentRoute: () => rootRouteImport,
} as any)
const OverthinkingRoute = OverthinkingRouteImport.update({
  id: '/overthinking',
  path: '/overthinking',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentingRoute = ParentingRouteImport.update({
  id: '/parenting',
  path: '/parenting',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalSessionRoute = PersonalSessionRouteImport.update({
  id: '/personal-session',
  path: '/personal-session',
  getParentRoute: () => rootRouteImport,
} as any)
const PositiveThinkingRoute = PositiveThinkingRouteImport.update({
  id: '/positive-thinking',
  path: '/positive-thinking',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationshipRoute = RelationshipRouteImport.update({
  id: '/relationship',
  path: '/relationship',
  getParentRoute: () => rootRouteImport,
} as any)
const SanjeevniKriyaRoute = SanjeevniKriyaRouteImport.update({
  id: '/sanjeevni-kriya',
  path: '/sanjeevni-kriya',
  getParentRoute: () => rootRouteImport,
} as any)
const SanjeevniKriya2Route = SanjeevniKriya2RouteImport.update({
  id: '/sanjeevni-kriya-2',
  path: '/sanjeevni-kriya-2',
  getParentRoute: () => rootRouteImport,
} as any)
const ScienceOfJoyfulLivingRoute = ScienceOfJoyfulLivingRouteImport.update({
  id: '/science-of-joyful-living',
  path: '/science-of-joyful-living',
  getParentRoute: () => rootRouteImport,
} as any)
const ScienceOfJoyfulLivingMarchRoute =
  ScienceOfJoyfulLivingMarchRouteImport.update({
    id: '/science-of-joyful-living-march',
    path: '/science-of-joyful-living-march',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShikshaSewaRoute = ShikshaSewaRouteImport.update({
  id: '/shiksha-sewa',
  path: '/shiksha-sewa',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SleepingDisorderRoute = SleepingDisorderRouteImport.update({
  id: '/sleeping-disorder',
  path: '/sleeping-disorder',
  getParentRoute: () => rootRouteImport,
} as any)
const StressRoute = StressRouteImport.update({
  id: '/stress',
  path: '/stress',
  getParentRoute: () => rootRouteImport,
} as any)
const SundayEvent1FebruaryRoute = SundayEvent1FebruaryRouteImport.update({
  id: '/sunday-event-1-february',
  path: '/sunday-event-1-february',
  getParentRoute: () => rootRouteImport,
} as any)
const SundayEvent1MarchRoute = SundayEvent1MarchRouteImport.update({
  id: '/sunday-event-1-march',
  path: '/sunday-event-1-march',
  getParentRoute: () => rootRouteImport,
} as any)
const SundayEvent3MayRoute = SundayEvent3MayRouteImport.update({
  id: '/sunday-event-3-may',
  path: '/sunday-event-3-may',
  getParentRoute: () => rootRouteImport,
} as any)
const SundayEvent4JanuaryRoute = SundayEvent4JanuaryRouteImport.update({
  id: '/sunday-event-4-january',
  path: '/sunday-event-4-january',
  getParentRoute: () => rootRouteImport,
} as any)
const SundayEvent5AprilRoute = SundayEvent5AprilRouteImport.update({
  id: '/sunday-event-5-april',
  path: '/sunday-event-5-april',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsConditionsRoute = TermsConditionsRouteImport.update({
  id: '/terms-conditions',
  path: '/terms-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const UsPersonalSessionRoute = UsPersonalSessionRouteImport.update({
  id: '/us-personal-session',
  path: '/us-personal-session',
  getParentRoute: () => rootRouteImport,
} as any)
const WellnessRoute = WellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => rootRouteImport,
} as any)
const YogaRoute = YogaRouteImport.update({
  id: '/yoga',
  path: '/yoga',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-movement': typeof AboutMovementRoute
  '/about-sakshi-shree': typeof AboutSakshiShreeRoute
  '/about-science-divine-movement': typeof AboutScienceDivineMovementRoute
  '/addictions': typeof AddictionsRoute
  '/annapurna-sewa': typeof AnnapurnaSewaRoute
  '/anxiety': typeof AnxietyRoute
  '/auth': typeof AuthRoute
  '/birthday-event': typeof BirthdayEventRoute
  '/book-session': typeof BookSessionRoute
  '/cancellation-and-refund-policy': typeof CancellationAndRefundPolicyRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/depression': typeof DepressionRoute
  '/design-your-destiny': typeof DesignYourDestinyRoute
  '/design-your-destiny-2': typeof DesignYourDestiny2Route
  '/designyourdestiny': typeof DesignyourdestinyRoute
  '/dhyan-sewa': typeof DhyanSewaRoute
  '/education-sewa': typeof EducationSewaRoute
  '/event-new': typeof EventNewRoute
  '/events': typeof EventsRoute
  '/events-gallery': typeof EventsGalleryRoute
  '/finding-purpose': typeof FindingPurposeRoute
  '/get-solutions-for': typeof GetSolutionsForRoute
  '/get-started-with': typeof GetStartedWithRoute
  '/gratitude': typeof GratitudeRoute
  '/har-ghar-shiksha': typeof HarGharShikshaRoute
  '/har-ghar-shiksha-volunteers': typeof HarGharShikshaVolunteersRoute
  '/initiatives': typeof InitiativesRoute
  '/latest-testimonials-videos': typeof LatestTestimonialsVideosRoute
  '/manifestation': typeof ManifestationRoute
  '/meditation': typeof MeditationRoute
  '/mind-power-meditation': typeof MindPowerMeditationRoute
  '/mindfulness': typeof MindfulnessRoute
  '/my-account': typeof MyAccountRoute
  '/nirman-sewa': typeof NirmanSewaRoute
  '/overthinking': typeof OverthinkingRoute
  '/parenting': typeof ParentingRoute
  '/personal-session': typeof PersonalSessionRoute
  '/positive-thinking': typeof PositiveThinkingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/relationship': typeof RelationshipRoute
  '/sanjeevni-kriya': typeof SanjeevniKriyaRoute
  '/sanjeevni-kriya-2': typeof SanjeevniKriya2Route
  '/science-of-joyful-living': typeof ScienceOfJoyfulLivingRoute
  '/science-of-joyful-living-march': typeof ScienceOfJoyfulLivingMarchRoute
  '/shiksha-sewa': typeof ShikshaSewaRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sleeping-disorder': typeof SleepingDisorderRoute
  '/stress': typeof StressRoute
  '/sunday-event-1-february': typeof SundayEvent1FebruaryRoute
  '/sunday-event-1-march': typeof SundayEvent1MarchRoute
  '/sunday-event-3-may': typeof SundayEvent3MayRoute
  '/sunday-event-4-january': typeof SundayEvent4JanuaryRoute
  '/sunday-event-5-april': typeof SundayEvent5AprilRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
  '/us-personal-session': typeof UsPersonalSessionRoute
  '/wellness': typeof WellnessRoute
  '/yoga': typeof YogaRoute
  '/admin': typeof AuthenticatedAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-movement': typeof AboutMovementRoute
  '/about-sakshi-shree': typeof AboutSakshiShreeRoute
  '/about-science-divine-movement': typeof AboutScienceDivineMovementRoute
  '/addictions': typeof AddictionsRoute
  '/annapurna-sewa': typeof AnnapurnaSewaRoute
  '/anxiety': typeof AnxietyRoute
  '/auth': typeof AuthRoute
  '/birthday-event': typeof BirthdayEventRoute
  '/book-session': typeof BookSessionRoute
  '/cancellation-and-refund-policy': typeof CancellationAndRefundPolicyRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/depression': typeof DepressionRoute
  '/design-your-destiny': typeof DesignYourDestinyRoute
  '/design-your-destiny-2': typeof DesignYourDestiny2Route
  '/designyourdestiny': typeof DesignyourdestinyRoute
  '/dhyan-sewa': typeof DhyanSewaRoute
  '/education-sewa': typeof EducationSewaRoute
  '/event-new': typeof EventNewRoute
  '/events': typeof EventsRoute
  '/events-gallery': typeof EventsGalleryRoute
  '/finding-purpose': typeof FindingPurposeRoute
  '/get-solutions-for': typeof GetSolutionsForRoute
  '/get-started-with': typeof GetStartedWithRoute
  '/gratitude': typeof GratitudeRoute
  '/har-ghar-shiksha': typeof HarGharShikshaRoute
  '/har-ghar-shiksha-volunteers': typeof HarGharShikshaVolunteersRoute
  '/initiatives': typeof InitiativesRoute
  '/latest-testimonials-videos': typeof LatestTestimonialsVideosRoute
  '/manifestation': typeof ManifestationRoute
  '/meditation': typeof MeditationRoute
  '/mind-power-meditation': typeof MindPowerMeditationRoute
  '/mindfulness': typeof MindfulnessRoute
  '/my-account': typeof MyAccountRoute
  '/nirman-sewa': typeof NirmanSewaRoute
  '/overthinking': typeof OverthinkingRoute
  '/parenting': typeof ParentingRoute
  '/personal-session': typeof PersonalSessionRoute
  '/positive-thinking': typeof PositiveThinkingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/relationship': typeof RelationshipRoute
  '/sanjeevni-kriya': typeof SanjeevniKriyaRoute
  '/sanjeevni-kriya-2': typeof SanjeevniKriya2Route
  '/science-of-joyful-living': typeof ScienceOfJoyfulLivingRoute
  '/science-of-joyful-living-march': typeof ScienceOfJoyfulLivingMarchRoute
  '/shiksha-sewa': typeof ShikshaSewaRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sleeping-disorder': typeof SleepingDisorderRoute
  '/stress': typeof StressRoute
  '/sunday-event-1-february': typeof SundayEvent1FebruaryRoute
  '/sunday-event-1-march': typeof SundayEvent1MarchRoute
  '/sunday-event-3-may': typeof SundayEvent3MayRoute
  '/sunday-event-4-january': typeof SundayEvent4JanuaryRoute
  '/sunday-event-5-april': typeof SundayEvent5AprilRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
  '/us-personal-session': typeof UsPersonalSessionRoute
  '/wellness': typeof WellnessRoute
  '/yoga': typeof YogaRoute
  '/admin': typeof AuthenticatedAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about-movement': typeof AboutMovementRoute
  '/about-sakshi-shree': typeof AboutSakshiShreeRoute
  '/about-science-divine-movement': typeof AboutScienceDivineMovementRoute
  '/addictions': typeof AddictionsRoute
  '/annapurna-sewa': typeof AnnapurnaSewaRoute
  '/anxiety': typeof AnxietyRoute
  '/auth': typeof AuthRoute
  '/birthday-event': typeof BirthdayEventRoute
  '/book-session': typeof BookSessionRoute
  '/cancellation-and-refund-policy': typeof CancellationAndRefundPolicyRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/depression': typeof DepressionRoute
  '/design-your-destiny': typeof DesignYourDestinyRoute
  '/design-your-destiny-2': typeof DesignYourDestiny2Route
  '/designyourdestiny': typeof DesignyourdestinyRoute
  '/dhyan-sewa': typeof DhyanSewaRoute
  '/education-sewa': typeof EducationSewaRoute
  '/event-new': typeof EventNewRoute
  '/events': typeof EventsRoute
  '/events-gallery': typeof EventsGalleryRoute
  '/finding-purpose': typeof FindingPurposeRoute
  '/get-solutions-for': typeof GetSolutionsForRoute
  '/get-started-with': typeof GetStartedWithRoute
  '/gratitude': typeof GratitudeRoute
  '/har-ghar-shiksha': typeof HarGharShikshaRoute
  '/har-ghar-shiksha-volunteers': typeof HarGharShikshaVolunteersRoute
  '/initiatives': typeof InitiativesRoute
  '/latest-testimonials-videos': typeof LatestTestimonialsVideosRoute
  '/manifestation': typeof ManifestationRoute
  '/meditation': typeof MeditationRoute
  '/mind-power-meditation': typeof MindPowerMeditationRoute
  '/mindfulness': typeof MindfulnessRoute
  '/my-account': typeof MyAccountRoute
  '/nirman-sewa': typeof NirmanSewaRoute
  '/overthinking': typeof OverthinkingRoute
  '/parenting': typeof ParentingRoute
  '/personal-session': typeof PersonalSessionRoute
  '/positive-thinking': typeof PositiveThinkingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/relationship': typeof RelationshipRoute
  '/sanjeevni-kriya': typeof SanjeevniKriyaRoute
  '/sanjeevni-kriya-2': typeof SanjeevniKriya2Route
  '/science-of-joyful-living': typeof ScienceOfJoyfulLivingRoute
  '/science-of-joyful-living-march': typeof ScienceOfJoyfulLivingMarchRoute
  '/shiksha-sewa': typeof ShikshaSewaRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sleeping-disorder': typeof SleepingDisorderRoute
  '/stress': typeof StressRoute
  '/sunday-event-1-february': typeof SundayEvent1FebruaryRoute
  '/sunday-event-1-march': typeof SundayEvent1MarchRoute
  '/sunday-event-3-may': typeof SundayEvent3MayRoute
  '/sunday-event-4-january': typeof SundayEvent4JanuaryRoute
  '/sunday-event-5-april': typeof SundayEvent5AprilRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
  '/us-personal-session': typeof UsPersonalSessionRoute
  '/wellness': typeof WellnessRoute
  '/yoga': typeof YogaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-movement'
    | '/about-sakshi-shree'
    | '/about-science-divine-movement'
    | '/addictions'
    | '/annapurna-sewa'
    | '/anxiety'
    | '/auth'
    | '/birthday-event'
    | '/book-session'
    | '/cancellation-and-refund-policy'
    | '/cancellation-policy'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/courses'
    | '/depression'
    | '/design-your-destiny'
    | '/design-your-destiny-2'
    | '/designyourdestiny'
    | '/dhyan-sewa'
    | '/education-sewa'
    | '/event-new'
    | '/events'
    | '/events-gallery'
    | '/finding-purpose'
    | '/get-solutions-for'
    | '/get-started-with'
    | '/gratitude'
    | '/har-ghar-shiksha'
    | '/har-ghar-shiksha-volunteers'
    | '/initiatives'
    | '/latest-testimonials-videos'
    | '/manifestation'
    | '/meditation'
    | '/mind-power-meditation'
    | '/mindfulness'
    | '/my-account'
    | '/nirman-sewa'
    | '/overthinking'
    | '/parenting'
    | '/personal-session'
    | '/positive-thinking'
    | '/privacy-policy'
    | '/relationship'
    | '/sanjeevni-kriya'
    | '/sanjeevni-kriya-2'
    | '/science-of-joyful-living'
    | '/science-of-joyful-living-march'
    | '/shiksha-sewa'
    | '/shop'
    | '/sitemap.xml'
    | '/sleeping-disorder'
    | '/stress'
    | '/sunday-event-1-february'
    | '/sunday-event-1-march'
    | '/sunday-event-3-may'
    | '/sunday-event-4-january'
    | '/sunday-event-5-april'
    | '/terms-and-conditions'
    | '/terms-conditions'
    | '/testimonials'
    | '/thank-you'
    | '/us-personal-session'
    | '/wellness'
    | '/yoga'
    | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-movement'
    | '/about-sakshi-shree'
    | '/about-science-divine-movement'
    | '/addictions'
    | '/annapurna-sewa'
    | '/anxiety'
    | '/auth'
    | '/birthday-event'
    | '/book-session'
    | '/cancellation-and-refund-policy'
    | '/cancellation-policy'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/courses'
    | '/depression'
    | '/design-your-destiny'
    | '/design-your-destiny-2'
    | '/designyourdestiny'
    | '/dhyan-sewa'
    | '/education-sewa'
    | '/event-new'
    | '/events'
    | '/events-gallery'
    | '/finding-purpose'
    | '/get-solutions-for'
    | '/get-started-with'
    | '/gratitude'
    | '/har-ghar-shiksha'
    | '/har-ghar-shiksha-volunteers'
    | '/initiatives'
    | '/latest-testimonials-videos'
    | '/manifestation'
    | '/meditation'
    | '/mind-power-meditation'
    | '/mindfulness'
    | '/my-account'
    | '/nirman-sewa'
    | '/overthinking'
    | '/parenting'
    | '/personal-session'
    | '/positive-thinking'
    | '/privacy-policy'
    | '/relationship'
    | '/sanjeevni-kriya'
    | '/sanjeevni-kriya-2'
    | '/science-of-joyful-living'
    | '/science-of-joyful-living-march'
    | '/shiksha-sewa'
    | '/shop'
    | '/sitemap.xml'
    | '/sleeping-disorder'
    | '/stress'
    | '/sunday-event-1-february'
    | '/sunday-event-1-march'
    | '/sunday-event-3-may'
    | '/sunday-event-4-january'
    | '/sunday-event-5-april'
    | '/terms-and-conditions'
    | '/terms-conditions'
    | '/testimonials'
    | '/thank-you'
    | '/us-personal-session'
    | '/wellness'
    | '/yoga'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about-movement'
    | '/about-sakshi-shree'
    | '/about-science-divine-movement'
    | '/addictions'
    | '/annapurna-sewa'
    | '/anxiety'
    | '/auth'
    | '/birthday-event'
    | '/book-session'
    | '/cancellation-and-refund-policy'
    | '/cancellation-policy'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/courses'
    | '/depression'
    | '/design-your-destiny'
    | '/design-your-destiny-2'
    | '/designyourdestiny'
    | '/dhyan-sewa'
    | '/education-sewa'
    | '/event-new'
    | '/events'
    | '/events-gallery'
    | '/finding-purpose'
    | '/get-solutions-for'
    | '/get-started-with'
    | '/gratitude'
    | '/har-ghar-shiksha'
    | '/har-ghar-shiksha-volunteers'
    | '/initiatives'
    | '/latest-testimonials-videos'
    | '/manifestation'
    | '/meditation'
    | '/mind-power-meditation'
    | '/mindfulness'
    | '/my-account'
    | '/nirman-sewa'
    | '/overthinking'
    | '/parenting'
    | '/personal-session'
    | '/positive-thinking'
    | '/privacy-policy'
    | '/relationship'
    | '/sanjeevni-kriya'
    | '/sanjeevni-kriya-2'
    | '/science-of-joyful-living'
    | '/science-of-joyful-living-march'
    | '/shiksha-sewa'
    | '/shop'
    | '/sitemap.xml'
    | '/sleeping-disorder'
    | '/stress'
    | '/sunday-event-1-february'
    | '/sunday-event-1-march'
    | '/sunday-event-3-may'
    | '/sunday-event-4-january'
    | '/sunday-event-5-april'
    | '/terms-and-conditions'
    | '/terms-conditions'
    | '/testimonials'
    | '/thank-you'
    | '/us-personal-session'
    | '/wellness'
    | '/yoga'
    | '/_authenticated/admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutMovementRoute: typeof AboutMovementRoute
  AboutSakshiShreeRoute: typeof AboutSakshiShreeRoute
  AboutScienceDivineMovementRoute: typeof AboutScienceDivineMovementRoute
  AddictionsRoute: typeof AddictionsRoute
  AnnapurnaSewaRoute: typeof AnnapurnaSewaRoute
  AnxietyRoute: typeof AnxietyRoute
  AuthRoute: typeof AuthRoute
  BirthdayEventRoute: typeof BirthdayEventRoute
  BookSessionRoute: typeof BookSessionRoute
  CancellationAndRefundPolicyRoute: typeof CancellationAndRefundPolicyRoute
  CancellationPolicyRoute: typeof CancellationPolicyRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  DepressionRoute: typeof DepressionRoute
  DesignYourDestinyRoute: typeof DesignYourDestinyRoute
  DesignYourDestiny2Route: typeof DesignYourDestiny2Route
  DesignyourdestinyRoute: typeof DesignyourdestinyRoute
  DhyanSewaRoute: typeof DhyanSewaRoute
  EducationSewaRoute: typeof EducationSewaRoute
  EventNewRoute: typeof EventNewRoute
  EventsRoute: typeof EventsRoute
  EventsGalleryRoute: typeof EventsGalleryRoute
  FindingPurposeRoute: typeof FindingPurposeRoute
  GetSolutionsForRoute: typeof GetSolutionsForRoute
  GetStartedWithRoute: typeof GetStartedWithRoute
  GratitudeRoute: typeof GratitudeRoute
  HarGharShikshaRoute: typeof HarGharShikshaRoute
  HarGharShikshaVolunteersRoute: typeof HarGharShikshaVolunteersRoute
  InitiativesRoute: typeof InitiativesRoute
  LatestTestimonialsVideosRoute: typeof LatestTestimonialsVideosRoute
  ManifestationRoute: typeof ManifestationRoute
  MeditationRoute: typeof MeditationRoute
  MindPowerMeditationRoute: typeof MindPowerMeditationRoute
  MindfulnessRoute: typeof MindfulnessRoute
  MyAccountRoute: typeof MyAccountRoute
  NirmanSewaRoute: typeof NirmanSewaRoute
  OverthinkingRoute: typeof OverthinkingRoute
  ParentingRoute: typeof ParentingRoute
  PersonalSessionRoute: typeof PersonalSessionRoute
  PositiveThinkingRoute: typeof PositiveThinkingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RelationshipRoute: typeof RelationshipRoute
  SanjeevniKriyaRoute: typeof SanjeevniKriyaRoute
  SanjeevniKriya2Route: typeof SanjeevniKriya2Route
  ScienceOfJoyfulLivingRoute: typeof ScienceOfJoyfulLivingRoute
  ScienceOfJoyfulLivingMarchRoute: typeof ScienceOfJoyfulLivingMarchRoute
  ShikshaSewaRoute: typeof ShikshaSewaRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SleepingDisorderRoute: typeof SleepingDisorderRoute
  StressRoute: typeof StressRoute
  SundayEvent1FebruaryRoute: typeof SundayEvent1FebruaryRoute
  SundayEvent1MarchRoute: typeof SundayEvent1MarchRoute
  SundayEvent3MayRoute: typeof SundayEvent3MayRoute
  SundayEvent4JanuaryRoute: typeof SundayEvent4JanuaryRoute
  SundayEvent5AprilRoute: typeof SundayEvent5AprilRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TermsConditionsRoute: typeof TermsConditionsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  ThankYouRoute: typeof ThankYouRoute
  UsPersonalSessionRoute: typeof UsPersonalSessionRoute
  WellnessRoute: typeof WellnessRoute
  YogaRoute: typeof YogaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-movement': {
      id: '/about-movement'
      path: '/about-movement'
      fullPath: '/about-movement'
      preLoaderRoute: typeof AboutMovementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-sakshi-shree': {
      id: '/about-sakshi-shree'
      path: '/about-sakshi-shree'
      fullPath: '/about-sakshi-shree'
      preLoaderRoute: typeof AboutSakshiShreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-science-divine-movement': {
      id: '/about-science-divine-movement'
      path: '/about-science-divine-movement'
      fullPath: '/about-science-divine-movement'
      preLoaderRoute: typeof AboutScienceDivineMovementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addictions': {
      id: '/addictions'
      path: '/addictions'
      fullPath: '/addictions'
      preLoaderRoute: typeof AddictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annapurna-sewa': {
      id: '/annapurna-sewa'
      path: '/annapurna-sewa'
      fullPath: '/annapurna-sewa'
      preLoaderRoute: typeof AnnapurnaSewaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anxiety': {
      id: '/anxiety'
      path: '/anxiety'
      fullPath: '/anxiety'
      preLoaderRoute: typeof AnxietyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/birthday-event': {
      id: '/birthday-event'
      path: '/birthday-event'
      fullPath: '/birthday-event'
      preLoaderRoute: typeof BirthdayEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-session': {
      id: '/book-session'
      path: '/book-session'
      fullPath: '/book-session'
      preLoaderRoute: typeof BookSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation-and-refund-policy': {
      id: '/cancellation-and-refund-policy'
      path: '/cancellation-and-refund-policy'
      fullPath: '/cancellation-and-refund-policy'
      preLoaderRoute: typeof CancellationAndRefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation-policy': {
      id: '/cancellation-policy'
      path: '/cancellation-policy'
      fullPath: '/cancellation-policy'
      preLoaderRoute: typeof CancellationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depression': {
      id: '/depression'
      path: '/depression'
      fullPath: '/depression'
      preLoaderRoute: typeof DepressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-your-destiny': {
      id: '/design-your-destiny'
      path: '/design-your-destiny'
      fullPath: '/design-your-destiny'
      preLoaderRoute: typeof DesignYourDestinyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-your-destiny-2': {
      id: '/design-your-destiny-2'
      path: '/design-your-destiny-2'
      fullPath: '/design-your-destiny-2'
      preLoaderRoute: typeof DesignYourDestiny2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designyourdestiny': {
      id: '/designyourdestiny'
      path: '/designyourdestiny'
      fullPath: '/designyourdestiny'
      preLoaderRoute: typeof DesignyourdestinyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dhyan-sewa': {
      id: '/dhyan-sewa'
      path: '/dhyan-sewa'
      fullPath: '/dhyan-sewa'
      preLoaderRoute: typeof DhyanSewaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education-sewa': {
      id: '/education-sewa'
      path: '/education-sewa'
      fullPath: '/education-sewa'
      preLoaderRoute: typeof EducationSewaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-new': {
      id: '/event-new'
      path: '/event-new'
      fullPath: '/event-new'
      preLoaderRoute: typeof EventNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events-gallery': {
      id: '/events-gallery'
      path: '/events-gallery'
      fullPath: '/events-gallery'
      preLoaderRoute: typeof EventsGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finding-purpose': {
      id: '/finding-purpose'
      path: '/finding-purpose'
      fullPath: '/finding-purpose'
      preLoaderRoute: typeof FindingPurposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-solutions-for': {
      id: '/get-solutions-for'
      path: '/get-solutions-for'
      fullPath: '/get-solutions-for'
      preLoaderRoute: typeof GetSolutionsForRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started-with': {
      id: '/get-started-with'
      path: '/get-started-with'
      fullPath: '/get-started-with'
      preLoaderRoute: typeof GetStartedWithRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gratitude': {
      id: '/gratitude'
      path: '/gratitude'
      fullPath: '/gratitude'
      preLoaderRoute: typeof GratitudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/har-ghar-shiksha': {
      id: '/har-ghar-shiksha'
      path: '/har-ghar-shiksha'
      fullPath: '/har-ghar-shiksha'
      preLoaderRoute: typeof HarGharShikshaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/har-ghar-shiksha-volunteers': {
      id: '/har-ghar-shiksha-volunteers'
      path: '/har-ghar-shiksha-volunteers'
      fullPath: '/har-ghar-shiksha-volunteers'
      preLoaderRoute: typeof HarGharShikshaVolunteersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initiatives': {
      id: '/initiatives'
      path: '/initiatives'
      fullPath: '/initiatives'
      preLoaderRoute: typeof InitiativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latest-testimonials-videos': {
      id: '/latest-testimonials-videos'
      path: '/latest-testimonials-videos'
      fullPath: '/latest-testimonials-videos'
      preLoaderRoute: typeof LatestTestimonialsVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifestation': {
      id: '/manifestation'
      path: '/manifestation'
      fullPath: '/manifestation'
      preLoaderRoute: typeof ManifestationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meditation': {
      id: '/meditation'
      path: '/meditation'
      fullPath: '/meditation'
      preLoaderRoute: typeof MeditationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mind-power-meditation': {
      id: '/mind-power-meditation'
      path: '/mind-power-meditation'
      fullPath: '/mind-power-meditation'
      preLoaderRoute: typeof MindPowerMeditationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mindfulness': {
      id: '/mindfulness'
      path: '/mindfulness'
      fullPath: '/mindfulness'
      preLoaderRoute: typeof MindfulnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-account': {
      id: '/my-account'
      path: '/my-account'
      fullPath: '/my-account'
      preLoaderRoute: typeof MyAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nirman-sewa': {
      id: '/nirman-sewa'
      path: '/nirman-sewa'
      fullPath: '/nirman-sewa'
      preLoaderRoute: typeof NirmanSewaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overthinking': {
      id: '/overthinking'
      path: '/overthinking'
      fullPath: '/overthinking'
      preLoaderRoute: typeof OverthinkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parenting': {
      id: '/parenting'
      path: '/parenting'
      fullPath: '/parenting'
      preLoaderRoute: typeof ParentingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-session': {
      id: '/personal-session'
      path: '/personal-session'
      fullPath: '/personal-session'
      preLoaderRoute: typeof PersonalSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positive-thinking': {
      id: '/positive-thinking'
      path: '/positive-thinking'
      fullPath: '/positive-thinking'
      preLoaderRoute: typeof PositiveThinkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relationship': {
      id: '/relationship'
      path: '/relationship'
      fullPath: '/relationship'
      preLoaderRoute: typeof RelationshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanjeevni-kriya': {
      id: '/sanjeevni-kriya'
      path: '/sanjeevni-kriya'
      fullPath: '/sanjeevni-kriya'
      preLoaderRoute: typeof SanjeevniKriyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanjeevni-kriya-2': {
      id: '/sanjeevni-kriya-2'
      path: '/sanjeevni-kriya-2'
      fullPath: '/sanjeevni-kriya-2'
      preLoaderRoute: typeof SanjeevniKriya2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/science-of-joyful-living': {
      id: '/science-of-joyful-living'
      path: '/science-of-joyful-living'
      fullPath: '/science-of-joyful-living'
      preLoaderRoute: typeof ScienceOfJoyfulLivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/science-of-joyful-living-march': {
      id: '/science-of-joyful-living-march'
      path: '/science-of-joyful-living-march'
      fullPath: '/science-of-joyful-living-march'
      preLoaderRoute: typeof ScienceOfJoyfulLivingMarchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shiksha-sewa': {
      id: '/shiksha-sewa'
      path: '/shiksha-sewa'
      fullPath: '/shiksha-sewa'
      preLoaderRoute: typeof ShikshaSewaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sleeping-disorder': {
      id: '/sleeping-disorder'
      path: '/sleeping-disorder'
      fullPath: '/sleeping-disorder'
      preLoaderRoute: typeof SleepingDisorderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stress': {
      id: '/stress'
      path: '/stress'
      fullPath: '/stress'
      preLoaderRoute: typeof StressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sunday-event-1-february': {
      id: '/sunday-event-1-february'
      path: '/sunday-event-1-february'
      fullPath: '/sunday-event-1-february'
      preLoaderRoute: typeof SundayEvent1FebruaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sunday-event-1-march': {
      id: '/sunday-event-1-march'
      path: '/sunday-event-1-march'
      fullPath: '/sunday-event-1-march'
      preLoaderRoute: typeof SundayEvent1MarchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sunday-event-3-may': {
      id: '/sunday-event-3-may'
      path: '/sunday-event-3-may'
      fullPath: '/sunday-event-3-may'
      preLoaderRoute: typeof SundayEvent3MayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sunday-event-4-january': {
      id: '/sunday-event-4-january'
      path: '/sunday-event-4-january'
      fullPath: '/sunday-event-4-january'
      preLoaderRoute: typeof SundayEvent4JanuaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sunday-event-5-april': {
      id: '/sunday-event-5-april'
      path: '/sunday-event-5-april'
      fullPath: '/sunday-event-5-april'
      preLoaderRoute: typeof SundayEvent5AprilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-conditions': {
      id: '/terms-conditions'
      path: '/terms-conditions'
      fullPath: '/terms-conditions'
      preLoaderRoute: typeof TermsConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/us-personal-session': {
      id: '/us-personal-session'
      path: '/us-personal-session'
      fullPath: '/us-personal-session'
      preLoaderRoute: typeof UsPersonalSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wellness': {
      id: '/wellness'
      path: '/wellness'
      fullPath: '/wellness'
      preLoaderRoute: typeof WellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yoga': {
      id: '/yoga'
      path: '/yoga'
      fullPath: '/yoga'
      preLoaderRoute: typeof YogaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutMovementRoute: AboutMovementRoute,
  AboutSakshiShreeRoute: AboutSakshiShreeRoute,
  AboutScienceDivineMovementRoute: AboutScienceDivineMovementRoute,
  AddictionsRoute: AddictionsRoute,
  AnnapurnaSewaRoute: AnnapurnaSewaRoute,
  AnxietyRoute: AnxietyRoute,
  AuthRoute: AuthRoute,
  BirthdayEventRoute: BirthdayEventRoute,
  BookSessionRoute: BookSessionRoute,
  CancellationAndRefundPolicyRoute: CancellationAndRefundPolicyRoute,
  CancellationPolicyRoute: CancellationPolicyRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  DepressionRoute: DepressionRoute,
  DesignYourDestinyRoute: DesignYourDestinyRoute,
  DesignYourDestiny2Route: DesignYourDestiny2Route,
  DesignyourdestinyRoute: DesignyourdestinyRoute,
  DhyanSewaRoute: DhyanSewaRoute,
  EducationSewaRoute: EducationSewaRoute,
  EventNewRoute: EventNewRoute,
  EventsRoute: EventsRoute,
  EventsGalleryRoute: EventsGalleryRoute,
  FindingPurposeRoute: FindingPurposeRoute,
  GetSolutionsForRoute: GetSolutionsForRoute,
  GetStartedWithRoute: GetStartedWithRoute,
  GratitudeRoute: GratitudeRoute,
  HarGharShikshaRoute: HarGharShikshaRoute,
  HarGharShikshaVolunteersRoute: HarGharShikshaVolunteersRoute,
  InitiativesRoute: InitiativesRoute,
  LatestTestimonialsVideosRoute: LatestTestimonialsVideosRoute,
  ManifestationRoute: ManifestationRoute,
  MeditationRoute: MeditationRoute,
  MindPowerMeditationRoute: MindPowerMeditationRoute,
  MindfulnessRoute: MindfulnessRoute,
  MyAccountRoute: MyAccountRoute,
  NirmanSewaRoute: NirmanSewaRoute,
  OverthinkingRoute: OverthinkingRoute,
  ParentingRoute: ParentingRoute,
  PersonalSessionRoute: PersonalSessionRoute,
  PositiveThinkingRoute: PositiveThinkingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RelationshipRoute: RelationshipRoute,
  SanjeevniKriyaRoute: SanjeevniKriyaRoute,
  SanjeevniKriya2Route: SanjeevniKriya2Route,
  ScienceOfJoyfulLivingRoute: ScienceOfJoyfulLivingRoute,
  ScienceOfJoyfulLivingMarchRoute: ScienceOfJoyfulLivingMarchRoute,
  ShikshaSewaRoute: ShikshaSewaRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SleepingDisorderRoute: SleepingDisorderRoute,
  StressRoute: StressRoute,
  SundayEvent1FebruaryRoute: SundayEvent1FebruaryRoute,
  SundayEvent1MarchRoute: SundayEvent1MarchRoute,
  SundayEvent3MayRoute: SundayEvent3MayRoute,
  SundayEvent4JanuaryRoute: SundayEvent4JanuaryRoute,
  SundayEvent5AprilRoute: SundayEvent5AprilRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TermsConditionsRoute: TermsConditionsRoute,
  TestimonialsRoute: TestimonialsRoute,
  ThankYouRoute: ThankYouRoute,
  UsPersonalSessionRoute: UsPersonalSessionRoute,
  WellnessRoute: WellnessRoute,
  YogaRoute: YogaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
