// Official and verified Science Divine internal navigation links
export const scienceDivineLinks = {
  home: "/",
  aboutMovement: "/about-movement",
  aboutSakshiShree: "/about-sakshi-shree",
  aboutScienceDivineMovement: "/about-science-divine-movement",
  courses: "/courses",
  designYourDestiny: "/design-your-destiny",
  scienceOfJoyfulLiving: "/science-of-joyful-living",
  mindPowerMeditation: "/mind-power-meditation",
  sanjeevaniKriya: "/sanjeevani-kriya",
  events: "/events",
  eventsGallery: "/events-gallery",
  initiatives: "/initiatives",
  shikshaSewa: "/shiksha-sewa",
  annapurnaSewa: "/annapurna-sewa",
  dhyanSewa: "/dhyan-sewa",
  nirmanSewa: "/nirman-sewa",
  harGharShiksha: "/har-ghar-shiksha",
  harGharShikshaVolunteers: "/har-ghar-shiksha-volunteers",
  solutions: "/get-solutions-for",
  stress: "/stress",
  anxiety: "/anxiety",
  depression: "/depression",
  overthinking: "/overthinking",
  sleepingDisorder: "/sleeping-disorder",
  parenting: "/parenting",
  addictions: "/addictions",
  relationship: "/relationship",
  meditation: "/meditation",
  yoga: "/yoga",
  mindfulness: "/mindfulness",
  gratitude: "/gratitude",
  manifestation: "/manifestation",
  positiveThinking: "/positive-thinking",
  findingPurpose: "/finding-purpose",
  wellness: "/wellness",
  bookSession: "/book-session",
  personalSession: "/personal-session",
  usPersonalSession: "/us-personal-session",
  shop: "/shop",
  contact: "/contact",
  testimonials: "/testimonials",
  latestTestimonialsVideos: "/latest-testimonials-videos",
  privacyPolicy: "/privacy-policy",
  termsConditions: "/terms-conditions",
  cancellationPolicy: "/cancellation-policy",
} as const;

export type ScienceDivineLinkKey = keyof typeof scienceDivineLinks;
